#!/usr/bin/env python3
"""
Generate .ai/index.yaml — a token-cheap routing index.

Reads all .ai/*.yaml files and emits a single, small YAML file listing:
  - Top-level summary (from context.yaml.summary, falling back to project.description)
  - Keys available in each file (component ids, workflow ids, ADR ids, error ids)
  - A routing table suggesting which file to load per query intent

Regenerate after edits:
    python generate_index.py .

Or via `make generate-index` / the AICaC adoption action.
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

import yaml


ROUTING_HINTS = {
    "project_overview": ["context.yaml"],
    "architecture": ["architecture.yaml"],
    "how_to": ["workflows.yaml"],
    "why_decision": ["decisions.yaml"],
    "error_troubleshooting": ["errors.yaml"],
    "deep_architecture": ["architecture.yaml", "decisions.yaml"],
}


def _load(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path) as fh:
        return yaml.safe_load(fh) or {}


def _keys_of(obj) -> list[str]:
    if isinstance(obj, dict):
        return sorted(obj.keys())
    if isinstance(obj, list):
        return [item.get("name") or item.get("id") or f"#{i}"
                for i, item in enumerate(obj) if isinstance(item, dict)]
    return []


def build_index(ai_dir: Path) -> dict:
    ctx = _load(ai_dir / "context.yaml")
    arch = _load(ai_dir / "architecture.yaml")
    wfs = _load(ai_dir / "workflows.yaml")
    adrs = _load(ai_dir / "decisions.yaml")
    errs = _load(ai_dir / "errors.yaml")

    project = ctx.get("project") or {}
    summary = ctx.get("summary") or project.get("description") or project.get("name", "")

    keys = {}
    # context: advertise top-level fields that exist
    keys["context"] = sorted(k for k in ctx.keys() if k not in {"schema", "version"})
    if arch:
        keys["architecture"] = _keys_of(arch.get("components"))
    if wfs:
        keys["workflows"] = _keys_of(wfs.get("workflows"))
    if adrs:
        keys["decisions"] = _keys_of(adrs.get("decisions"))
    if errs:
        keys["errors"] = _keys_of(errs.get("errors")) or _keys_of(errs.get("error_patterns"))

    return {
        "version": "2.0",
        "generated": datetime.datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "summary": summary,
        "keys": keys,
        "routing": ROUTING_HINTS,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate .ai/index.yaml")
    parser.add_argument("project_path", nargs="?", default=".")
    parser.add_argument("--check", action="store_true",
                        help="Fail non-zero if regeneration would change the file.")
    parser.add_argument("--stdout", action="store_true",
                        help="Print to stdout instead of writing.")
    args = parser.parse_args()

    ai_dir = Path(args.project_path) / ".ai"
    if not ai_dir.exists():
        print(f"No .ai/ at {ai_dir}", file=sys.stderr)
        return 1

    idx = build_index(ai_dir)
    out = yaml.safe_dump(idx, default_flow_style=False, sort_keys=False, allow_unicode=True)
    # preserve a header comment
    out = "# AUTO-GENERATED by generate_index.py. Do not hand-edit.\n" + out

    target = ai_dir / "index.yaml"

    if args.stdout:
        print(out)
        return 0

    if args.check:
        existing = target.read_text() if target.exists() else ""
        if existing.strip() != out.strip():
            print(f"{target} is out of date. Regenerate with: "
                  f"python {Path(__file__).name} .", file=sys.stderr)
            return 1
        print(f"{target} is up to date.")
        return 0

    target.write_text(out)
    print(f"Wrote {target} ({len(idx['keys'])} file groups, "
          f"{sum(len(v) for v in idx['keys'].values())} keys).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
