#!/usr/bin/env python3
"""
AICaC TOON Generator

Generates TOON (Token-Oriented Object Notation) files from .ai/ YAML sources.
YAML remains the human-authored source-of-truth; TOON files are generated
artifacts optimized for AI consumption.

Usage:
  python generate_toon.py [project_path]
  python generate_toon.py [project_path] --check   # dry-run, exit 1 if stale
  python generate_toon.py [project_path] --clean    # remove generated .toon files
"""

import sys
import hashlib
from pathlib import Path
from typing import Optional

import yaml

try:
    from toon_format import encode as toon_encode
    HAS_TOON = True
except ImportError:
    HAS_TOON = False


TOON_HEADER = "# AUTO-GENERATED by AICaC — do not edit. Source: .ai/{source}\n"


def yaml_to_toon(yaml_path: Path) -> Optional[str]:
    """Convert a single YAML file to TOON string."""
    with open(yaml_path) as f:
        data = yaml.safe_load(f)

    if data is None:
        return None

    header = TOON_HEADER.format(source=yaml_path.name)
    return header + toon_encode(data)


def checksum(text: str) -> str:
    """SHA-256 of content for staleness detection."""
    return hashlib.sha256(text.encode()).hexdigest()[:12]


def generate(project_path: Path, check_only: bool = False) -> dict:
    """Generate .toon files for every .ai/*.yaml file.

    Returns a dict with keys: generated, skipped, stale, errors.
    """
    ai_dir = project_path / ".ai"
    if not ai_dir.exists():
        print("No .ai/ directory found — nothing to generate.")
        return {"generated": 0, "skipped": 0, "stale": [], "errors": []}

    yaml_files = sorted(ai_dir.glob("*.yaml"))
    if not yaml_files:
        print("No .yaml files in .ai/ — nothing to generate.")
        return {"generated": 0, "skipped": 0, "stale": [], "errors": []}

    generated = 0
    skipped = 0
    stale = []
    errors = []

    for yaml_path in yaml_files:
        toon_path = yaml_path.with_suffix(".toon")
        try:
            toon_content = yaml_to_toon(yaml_path)
        except Exception as e:
            errors.append(f"{yaml_path.name}: {e}")
            continue

        if toon_content is None:
            skipped += 1
            continue

        if toon_path.exists():
            existing = toon_path.read_text()
            if existing == toon_content:
                skipped += 1
                continue
            stale.append(yaml_path.name)

        if not check_only:
            toon_path.write_text(toon_content)
            generated += 1
            print(f"  Generated .ai/{toon_path.name}")
        else:
            stale.append(yaml_path.name)

    return {
        "generated": generated,
        "skipped": skipped,
        "stale": stale,
        "errors": errors,
    }


def clean(project_path: Path) -> int:
    """Remove all generated .toon files from .ai/ directory."""
    ai_dir = project_path / ".ai"
    if not ai_dir.exists():
        return 0

    removed = 0
    for toon_path in sorted(ai_dir.glob("*.toon")):
        toon_path.unlink()
        print(f"  Removed .ai/{toon_path.name}")
        removed += 1

    return removed


def print_report(result: dict, check_only: bool = False):
    """Print a summary of the generation run."""
    print()
    print("=" * 50)
    print("AICaC TOON Generation Report")
    print("=" * 50)

    if check_only:
        if result["stale"]:
            print(f"\nStale TOON files ({len(result['stale'])}):")
            for name in result["stale"]:
                print(f"  - .ai/{name} needs regeneration")
        else:
            print("\nAll TOON files are up to date.")
    else:
        print(f"\n  Generated: {result['generated']}")
        print(f"  Skipped (unchanged): {result['skipped']}")

    if result["errors"]:
        print(f"\n  Errors ({len(result['errors'])}):")
        for err in result["errors"]:
            print(f"    - {err}")

    print("=" * 50)


def main():
    args = sys.argv[1:]

    project_path = Path(".")
    check_only = False
    do_clean = False

    for arg in args:
        if arg == "--check":
            check_only = True
        elif arg == "--clean":
            do_clean = True
        elif not arg.startswith("--"):
            project_path = Path(arg)

    if not HAS_TOON:
        print(
            "toon_format not installed. Install with:\n"
            "  pip install git+https://github.com/toon-format/toon-python.git"
        )
        sys.exit(1)

    if do_clean:
        removed = clean(project_path)
        print(f"Removed {removed} .toon file(s).")
        sys.exit(0)

    result = generate(project_path, check_only=check_only)
    print_report(result, check_only=check_only)

    if check_only and result["stale"]:
        sys.exit(1)

    if result["errors"]:
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
